---
pool:
  name: "Azure Pipelines" 
  vmImage: 'ubuntu-latest'

trigger: 
  - develop

parameters:
- name: image
  displayName: dotnet
  type: string
  default: build
  values:
    - build
    - push
    - pack
    - publish 

steps:
  - task: DotNetCoreCLI@1
    inputs:
      command: ${{ parameters.image }}
      
      